spring:
  messages:
    basename: i18n.login
  datasource:
#   数据源基本配置
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/qq?characterEncoding=UTF-8&serverTimezone=GMT%2B8
server:
  port: 8080
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml
